# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/js/dom.nim
# rdoccmd: -b:js -r:off
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/dom_examples_1.nim"
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/dom_examples_2.nim"
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/dom_examples_3.nim"
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/dom_examples_4.nim"
