#[
autogenerated by docgen
loc: /home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim(133, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim", 133, 3).}:
  doAssert (big"555" xor big"2") == big"553"

