#[
autogenerated by docgen
loc: /home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim(73, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/nim-wasi/nim-wasi/lib/std/jsbigints.nim", 73, 3).}:
  doAssert (big"9" + big"1") == big"10"

