# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/js/jscore.nim
# rdoccmd: 
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jscore_examples_1.nim"
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jscore_examples_2.nim"
