# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/js/jscore.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jscore_examples_3.nim"
