# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/js/jsconsole.nim
# rdoccmd: 
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jsconsole_examples_2.nim"
