# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/std/jsfetch.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jsfetch_examples_1.nim"
