# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/js/jsffi.nim
# rdoccmd: 
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jsffi_examples_1.nim"
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jsffi_examples_2.nim"
