# autogenerated by docgen
# source: /home/runner/work/nim-wasi/nim-wasi/lib/std/jsformdata.nim
# rdoccmd: -r:off
import "/home/runner/work/nim-wasi/nim-wasi/doc/html/nimcache/runnableExamples/jsformdata_examples_1.nim"
