#[
autogenerated by docgen
loc: /home/runner/work/nim-wasi/nim-wasi/lib/js/jsre.nim(72, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/nim-wasi/nim-wasi/lib/js/jsre.nim"
{.line: ("/home/runner/work/nim-wasi/nim-wasi/lib/js/jsre.nim", 72, 3).}:
  let jsregex: RegExp = newRegExp(r"bcd", r"i")
  assert "abcd".endsWith jsregex

